"""melhorias: versao, presenca, revelacao, rolagens, arquivos

Revision ID: 0002_melhorias
Revises: 0001_inicial
Create Date: 2026-09-16 19:45:21.739674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_melhorias'
down_revision = '0001_inicial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('filename', sa.String(length=80), nullable=False),
    sa.Column('mimetype', sa.String(length=40), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_token'), ['token'], unique=True)

    op.create_table('note_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'user_id', name='uq_note_recipient')
    )
    op.create_table('roll_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.String(length=400), nullable=True),
    sa.Column('flag', sa.String(length=8), nullable=True),
    sa.Column('secret', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roll_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roll_logs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roll_logs_created_at'), ['created_at'], unique=False)

    op.create_table('session_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_attendance')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=5), nullable=True))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revealed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('revealed_at')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('version')

    op.drop_table('session_attendance')
    with op.batch_alter_table('roll_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roll_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_roll_logs_campaign_id'))

    op.drop_table('roll_logs')
    op.drop_table('note_recipients')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_token'))

    op.drop_table('assets')
    # ### end Alembic commands ###
