"""historico da ficha e tentativas de login

Revision ID: 0003_historico_login
Revises: 0002_melhorias
Create Date: 2026-09-18 19:40:57.747534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_historico_login'
down_revision = '0002_melhorias'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=160), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)

    op.create_table('character_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('changed', sa.String(length=300), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_revisions_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_revisions_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_revisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_character_revisions_character_id'))

    op.drop_table('character_revisions')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_identifier'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
