"""ferramentas do mestre e da mesa

Revision ID: 0006_ferramentas
Revises: 0005_mesa_viva
Create Date: 2026-09-19 11:00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006_ferramentas'
down_revision = '0005_mesa_viva'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=40), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('first_at', sa.DateTime(), nullable=True),
    sa.Column('last_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    with op.batch_alter_table('error_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_reports_last_at'), ['last_at'], unique=False)

    op.create_table('site_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('random_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('entries', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('random_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_random_tables_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('whispers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whispers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whispers_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_encounters_session_id', 'game_sessions', ['session_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminded_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('reminded_at')

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_encounters_session_id', type_='foreignkey')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('whispers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whispers_campaign_id'))

    op.drop_table('whispers')
    with op.batch_alter_table('random_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_random_tables_campaign_id'))

    op.drop_table('random_tables')
    op.drop_table('site_settings')
    with op.batch_alter_table('error_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_reports_last_at'))

    op.drop_table('error_reports')
    # ### end Alembic commands ###
